version: "3" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
    homaale: #This is the name of our Nextjs application.
        container_name: homaale-ui
        build: #This specifies the location of our Dockerfile
            context: . #This specifies the location of our Dockerfile
        ports: #This is used to map the container’s ports to the host machine.
            - "8020:8020"
        restart: unless-stopped
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.60'
        #             memory: 2G
        #         reservations:
        #             cpus: '0.70'
        #             memory: 3G
