export const helpCardContent = [
    {
        id: "0",
        cardTitle: "Homaale Registration",
        cardImage: "/help-icons/homaale-registration.png",
        cardDescription: "",
        redirect: "/faq",
        query: "Homaale Registration",
    },
    {
        id: "1",
        cardTitle: "Payment Help",
        cardImage: "/help-icons/payment-help.png",
        cardDescription: "",
        redirect: "/faq",
        query: "Payment",
    },
    {
        id: "2",
        cardTitle: "Report a Problem",
        cardImage: "/help-icons/report-problem.png",
        cardDescription: "",
        redirect: "/feedback",
        query: "",
    },
    {
        id: "0",
        cardTitle: "Safety and Privacy",
        cardImage: "/help-icons/safety.png",
        cardDescription: "",
        redirect: "/privacy-policy",
        query: "",
    },
    {
        id: "0",
        cardTitle: "KYC Help",
        cardImage: "/help-icons/kyc-help.png",
        cardDescription: "",
        redirect: "/faq",
        query: "KYC",
    },
    {
        id: "0",
        cardTitle: "Profile Help",
        cardImage: "/help-icons/account-status.png",
        cardDescription: "",
        redirect: "/faq",
        query: "Account and Profile",
    },
];
