export const merchants =[
    {
        id:"0",
        merchantImage:"/merchants/m1.png",
        merchantName:"Swostika Shrestha",
        merchantCategory:"Teacher",
        merchantLocation:"Balaju, KTM",
        merchantDescription:"I’m punctual and hardworking person. I love teaching what I ",
        merchantRating:"3.8(400)",
        merchantPrice:60,
    },
    {
        id:"1",
        merchantImage:"/merchants/m1.png",
        merchantName:"Greenery Go",
        merchantCategory:"Gardener",
        merchantLocation:"Jawlakhel, Lalitpur",
        merchantDescription:"We are a team of great individuals who believe in providing best services to",
        merchantRating:"4.3(200)",
        merchantPrice:40,
    },
    {
        id:"2",
        merchantImage:"/merchants/m1.png",
        merchantName:"Krishna Jha",
        merchantCategory:"  Personal Trainer",
        merchantLocation:"Maitighar , KTM",
        merchantDescription:"I’m a fitness trainer who has been in this field for around 5 years. I give my work the ",
        merchantRating:"4(600)",
        merchantPrice:70,
    },
    {
        id:"3",
        merchantImage:"/merchants/m1.png",
        merchantName:"Vibe & Wave Dance Classes",
        merchantCategory:"Training Classes",
        merchantLocation:"Ratoghar, Dhulikhel",
        merchantDescription:"Our team focuses on creativity and teaching innovative dance",
        merchantRating:"3(500)",
        merchantPrice:60,
    },
]