export const merchants =[
    {
        id:"0",
        merchantImage:"/merchants/m1.png",
        merchantName:"Swostika Shrestha",
        merchantCategory:"Teacher",
        merchantLocation:"Balaju, KTM",
        merchantDescription:"I’m punctual and hardworking person. I love teaching what I. We want  a garden cleaner for our bunglow.",
        merchantRating:"3.8(400)",
        merchantPrice:60,
        happyClients:200,
        successRate:90,
    },
    {
        id:"1",
        merchantImage:"/merchants/m1.png",
        merchantName:"Greenery Go",
        merchantCategory:"Gardener",
        merchantLocation:"Jawlakhel, Lalitpur",
        merchantDescription:"I’m punctual and hardworking person. I love teaching what I. We want  a garden cleaner for our bunglow who can great take care of our plants.",
        merchantRating:"4.3(200)",
        merchantPrice:40,
        happyClients:200,
        successRate:90,
    },
    {
        id:"2",
        merchantImage:"/merchants/m1.png",
        merchantName:"Krishna Jha",
        merchantCategory:"  Personal Trainer",
        merchantLocation:"Maitighar , KTM",
        merchantDescription:"We are a team of great individuals who believe in providing best services to. We want  a garden cleaner for our bunglow who can great take care",
        merchantRating:"4(600)",
        merchantPrice:70,
        happyClients:200,
        successRate:90,
    },
    {
        id:"3",
        merchantImage:"/merchants/m1.png",
        merchantName:"Vibe & Wave Dance Classes",
        merchantCategory:"Training Classes",
        merchantLocation:"Ratoghar, Dhulikhel",
        merchantDescription:"Our team focuses on creativity and teaching innovative dance. We want  a garden cleaner for our bunglow who can great take care of our plants, includes monitoring.",
        merchantRating:"3(500)",
        merchantPrice:60,
        happyClients:200,
        successRate:90,
    },
]