export const services = [
    {
        id:"0",
        serviceImage:"/services/s1.png",
        serviceTitle:"Harry Plumbing Service",
        serviceProvider:"Harry Smith",
        serviceProviderLocation:"Baneshwor, KTM",
        serviceDescription:"Gardener responsibilities include monitoring the health of all the planets",
        serviceRating:"4.8(200)",
        servicePrice:"50",
        hasOffer:true,
        discountRate:20,
    },
    {
        id:"1",
        serviceImage:"/services/s2.png",
        serviceTitle:"House Cleaner",
        serviceProvider:"Harry Smith",
        serviceProviderLocation:"Baneshwor, KTM",
        serviceDescription:"Gardener responsibilities include monitoring the health of all the planets",
        serviceRating:"4.8(200)",
        servicePrice:"50",
        hasOffer:false,
    },
    {
        id:"2",
        serviceImage:"/services/s3.png",
        serviceTitle:"Home Tution",
        serviceProvider:"Harry Smith",
        serviceProviderLocation:"Baneshwor, KTM",
        serviceDescription:"Gardener responsibilities include monitoring the health of all the planets",
        serviceRating:"4.8(200)",
        servicePrice:"50",
        hasOffer:false,
    },
    {
        id:"3",
        serviceImage:"/services/s4.png",
        serviceTitle:"Training Classes",
        serviceProvider:"Harry Smith",
        serviceProviderLocation:"Baneshwor, KTM",
        serviceDescription:"Gardener responsibilities include monitoring the health of all the planets",
        serviceRating:"4.8(200)",
        servicePrice:"50",
        hasOffer:true,
        discountRate:20,
        discountOn: "On Service Charges"
    },

]


export const servicesDiscover = [
    {
        id:"0",
        serviceImage:"/discover/service1.svg",
        serviceTitle:"Gardern Cleaner",
        serviceProvider:"Lalit Kumar",
        serviceProviderLocation:"Bagbazar, KTM",
        serviceDescription:"The novice gardener may wonder exactly when to do each project. It is common",
        serviceRating:"4.5(200)",
        servicePrice:"30",
        hasOffer:true,
        discountRate:20,
    },
    {
        id:"1",
        serviceImage:"/discover/service2.svg",
        serviceTitle:"Yoga Instructore",
        serviceProvider:"Shusma Karki",
        serviceProviderLocation:"Shantinagar, Banepa",
        serviceDescription:"A yoga practitioner with a dedicated yoga practice is a yogi...",
        serviceRating:"3(200)",
        servicePrice:"40",
        hasOffer:false,
    },
    {
        id:"2",
        serviceImage:"/discover/service3.svg",
        serviceTitle:"Makepup",
        serviceProvider:"Sanam Shrestha",
        serviceProviderLocation:"Buddhanagar, KTM",
        serviceDescription:"Makeup Geek Cosmetics offers professional quality, cruelty-free, ethically",
        serviceRating:"4(300)",
        servicePrice:"80",
        hasOffer:false,
    },
    {
        id:"3",
        serviceImage:"/discover/service4.svg",
        serviceTitle:"Training Classes",
        serviceProvider:"Sneha Vocal Class",
        serviceProviderLocation:"Baneshwor, KTM",
        serviceDescription:"Many organisations offer free online learning in a range of subjects and...",
        serviceRating:"4.7(1000)",
        servicePrice:"80",
        hasOffer:true,
        discountRate:20,
        discountOn: "On Service Charges"
    },

]