export const servicesNearYou = [
  {
    id: '0',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    haveDiscount: false,
    serviceRating: '4.5(200)',
    image: '/services/s1.png',
  },
  {
    id: '1',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'House Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '2',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Bike Rider',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '3',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '4',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '5',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '6',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '7',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '8',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '9',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '10',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '11',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Ac Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '12',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
  {
    id: '13',
    serviceProvider: 'Lalit Kumar',
    serviceTitle: 'Garden Cleaner',
    serviceProviderLocation: 'Buddhanagar, Kathmandu',
    servicePrice: 1000,
    serviceRating: '4.5(200)',
    haveDiscount: true,
    discount: 20,
    image: '/services/s1.png',
    discountOn: 'Service Charge',
  },
]
export type ServiceNearYou = typeof servicesNearYou[0]
