export const servicesNearYou = [
    {
        id: "0",
        serviceProvider: "Eleven",
        serviceTitle: "Learn Telepathy",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 100000,
        haveDiscount: false,
        serviceRating: "4.5(200)",
        image: "/services/s1.png",
    },
    {
        id: "1",
        serviceProvider: "Demogordon",
        serviceTitle: "Destroy Bugs",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "2",
        serviceProvider: "Ghachin Aryal",
        serviceTitle: "learn Coding",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "3",
        serviceProvider: "Tanjirou",
        serviceTitle: "Water form",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "4",
        serviceProvider: "Zenitsu",
        serviceTitle: "Lightening form",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "5",
        serviceProvider: "Uzumaki naruto",
        serviceTitle: "Martial arts ",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "6",
        serviceProvider: "Uchiha Itachi",
        serviceTitle: "Tax Payer",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "7",
        serviceProvider: "Eren Yaeger",
        serviceTitle: "Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "8",
        serviceProvider: "Mikasa Ackerman",
        serviceTitle: "BodyGuard",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "9",
        serviceProvider: "Lalit Kumar",
        serviceTitle: "Garden Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "10",
        serviceProvider: "Lalit Kumar",
        serviceTitle: "Garden Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "11",
        serviceProvider: "Lalit Kumar",
        serviceTitle: "Ac Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 1000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "12",
        serviceProvider: "Lalit Kumar",
        serviceTitle: "Garden Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 15000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
    {
        id: "13",
        serviceProvider: "Lalit Kumar",
        serviceTitle: "Garden Cleaner",
        serviceProviderLocation: "Buddhanagar, Kathmandu",
        servicePrice: 2000,
        serviceRating: "4.5(200)",
        haveDiscount: true,
        discount: 20,
        image: "/services/s1.png",
        discountOn: "Service Charge",
    },
];
export type ServiceNearYou = typeof servicesNearYou[0];
