export type ApprovedTaskProps = {
    total_pages: number;
    count: number;
    current: number;
    next: any;
    previous: any;
    page_size: number;
    result: Array<{
        id: string;
        assigner: {
            id: string;
            username: string;
            email: string;
            phone: any;
            first_name: string;
            middle_name: string;
            last_name: string;
            profile_image: string;
            bio: string;
        };
        assignee: {
            id: string;
            username: string;
            email: string;
            phone: any;
            first_name: string;
            middle_name: string;
            last_name: string;
            profile_image: string;
            bio: string;
        };
        created_at: string;
        updated_at: string;
        is_active: boolean;
        status: string;
        title: string;
        description: string;
        requirements: string;
        charge: number;
        location: string;
        estimated_time: number;
        slug: string;
        start_date: string;
        end_date: string;
        start_time: string;
        end_time?: string;
        extra_data: Array<any>;
        entity_service: string;
        booking: number;
        currency: number;
        city: number;
        images: Array<any>;
        videos: Array<any>;
    }>;
};
