import FormButton from "@components/common/FormButton";
import PasswordField from "@components/common/PasswordField";
import SwitchValue from "@components/common/SwitchValue";
import { PostCard } from "@components/PostTask/PostCard";
import { faPencil, faSquareCheck } from "@fortawesome/pro-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Field, Form, Formik } from "formik";
import { useChangePassword } from "hooks/profile/changePassword/useChangePassword";
import React from "react";
import Button from "react-bootstrap/Button";
import { toast } from "react-toastify";
import { useToggleSuccessModal } from "store/use-success-modal";
import { ChangePasswordFromData } from "utils/formData";
import changePasswordFormSchema from "utils/formValidation/changePasswordFormValidation";
import { isSubmittingClass } from "utils/helpers";

const ChangePasswordForm = () => {
    const toggleSuccessModal = useToggleSuccessModal();
    const { mutate } = useChangePassword();

    return (
        <>
            {/* Modal component */}
            <div className="account-form">
                <h2>Password</h2>
                <p>Password Configurations</p>
                <Formik
                    initialValues={ChangePasswordFromData}
                    validationSchema={changePasswordFormSchema}
                    onSubmit={async (values, action) => {
                        const { old_password, new_password } = values;
                        mutate(
                            { old_password, new_password },
                            {
                                onSuccess: () => {
                                    toast.success(
                                        "Password changed successfully"
                                    );
                                },
                                onError: (err) => {
                                    toast.error(err.message);
                                },
                            }
                        );
                        // toggleSuccessModal();
                        // To be used for API
                        // try {
                        //     axiosClient.post("/routes", values);
                        // } catch (error: any) {
                        //     error.response.data.message;
                        // }
                        console.log(values);
                        action.resetForm();
                    }}
                >
                    {({ isSubmitting, errors, touched, resetForm }) => (
                        <Form autoComplete="off">
                            {/* <pre>{JSON.stringify(errors, null, 4)}</pre> */}
                            <PasswordField
                                name="old_password"
                                typeOf="password"
                                labelName="Current Password"
                                error={errors.old_password}
                                touch={touched.old_password}
                                placeHolder="Current Password"
                            />
                            <PasswordField
                                typeOf="password"
                                name="new_password"
                                labelName="New Password"
                                error={errors.new_password}
                                touch={touched.new_password}
                                placeHolder="New Password"
                            />
                            <PasswordField
                                name="confirm_password"
                                typeOf="password"
                                labelName="Confirm Password"
                                error={errors.confirm_password}
                                touch={touched.confirm_password}
                                placeHolder="Confirm Password"
                            />
                            <h2 className="mt-5">2 Factor Authentication</h2>
                            <p>
                                Add an extra layer of security to block
                                unauthorized access and protect your account.
                            </p>
                            <h2>Authenticator App Code</h2>
                            <div className="d-flex justify-content-between security-toggle">
                                Enter a code generated by your authenticator app
                                to confirm it’s you.
                                <SwitchValue />
                            </div>
                            <h2>Authenticator App Code</h2>
                            <div className="d-flex justify-content-between security-toggle">
                                Receive a prompt from your mobile app to confirm
                                it’s you.
                                <SwitchValue />
                            </div>
                            <h2>Text Message</h2>
                            <div className="d-flex justify-content-between security-toggle">
                                Receive a four digit code by text message to
                                confirm it’s you.
                                <SwitchValue />
                            </div>
                            <div className="d-flex justify-content-between security-toggle">
                                <h2>Security Question</h2>
                                <FontAwesomeIcon
                                    icon={faPencil}
                                    className="svg-icon"
                                />
                            </div>
                            <p className="mb-3 d-flex align-content-center">
                                <Field
                                    type="checkbox"
                                    name="toggle"
                                    className="checkbox me-2"
                                />{" "}
                                Enabled
                            </p>
                            <p>
                                Answer a question you choose to confirm it’s
                                you.
                            </p>
                            <div className="d-flex justify-content-end">
                                <Button
                                    className="me-3 mb-0 cancel-btn"
                                    onClick={() => resetForm}
                                >
                                    Cancel
                                </Button>
                                <FormButton
                                    type="submit"
                                    variant="primary"
                                    name="Save"
                                    className="submit-btn w-25"
                                    isSubmitting={isSubmitting}
                                    isSubmittingClass={isSubmittingClass(
                                        isSubmitting
                                    )}
                                />
                            </div>
                        </Form>
                    )}
                </Formik>
            </div>
            <PostCard
                text="You are good to continue."
                buttonName="Continue"
                type="Success"
                iconName={faSquareCheck}
            />
        </>
    );
};
export default ChangePasswordForm;
